CREATE TABLE pessoa (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	logradouro VARCHAR(50),
	numero VARCHAR(10),
	complemento VARCHAR(50),
	bairro VARCHAR(30),
	cep VARCHAR(15),
	cidade VARCHAR(40),
	estado VARCHAR(10),
	ativo BOOLEAN NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET = utf8;

